data:
  train_files: /home/gaash/Wasif/Seg-Zero/data/MOT_grounding_Dataset/hf_dataset_mcp_new
  val_files: None
  prompt_key: problem
  max_prompt_length: 1300
  max_response_length: 2000
  rollout_batch_size: 1
  shuffle: true
  seed: 42
  max_pixels: 12845056
  min_pixels: 3136

algorithm:
  adv_estimator: grpo
  kl_coef: 0.0
  use_kl_prcp: true
  kl_penalty: "kl"
  tapo_stratergy: "freeze"
  tapo_keep_prob: 0.7
  tapo_interval: 2
  tapo_kl_weight: 0.1

worker:
  actor:
    global_batch_size: 1
    micro_batch_size_per_device_for_update: 1
    micro_batch_size_per_device_for_experience: 1
    max_grad_norm: 1.0
    use_kl_loss: true
    kl_loss_coef: 5.0e-3
    kl_loss_type: low_var_kl
    model:
      model_path: /home/gaash/Wasif/Seg-Zero/pretrained_models/Qwen2.5-VL-3B-Instruct
      enable_gradient_checkpointing: true

    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
    fsdp:
      param_offload: false       
      optimizer_offload: false    
      torch_dtype: null
    offload:
      param_offload: true
      optimizer_offload: true
      
  rollout:
    temperature: 1.0
    tensor_parallel_size: 1     
    gpu_memory_utilization: 0.9
    n: 8
    enable_chunked_prefill: false 
    limit_images: 2

  ref:
    offload:
      param_offload: true        

  reward:
    reward_type: function
    compute_score: vision_reasoner

trainer:
  total_episodes: 4
  logger: ["console"]
  project_name: vision_reasoner
  n_gpus_per_node: 1            
  save_freq: 1028
  test_freq: 10000
  val_before_train: false
  val_only: false